### ISSUE TITLE
Source code link error

### ISSUE THREAD

**Issue by PrasannaJayanthi** [astropy/photutils#1026] opened 2020-04-06 15:54 UTC
I was looking at the tutorials on the photutils website and there is an error in the source code link. There are two slashes instead of one. This is the current link "https://photutils.readthedocs.io/en/stable//background-1.py", it works if the link is this "https://photutils.readthedocs.io/en/stable/background-1.py". I am assuming the issue is the same for all the source code links.

**Comment by bsipocz** [comment] 2020-04-06 16:18
Thanks for the report.

It's an interesting `plot::` directive issue. Interestingly I don't see it in another package, but indeed it's persistently present in photutils.

@larrybradley @pllim - would you think that we can linkcheck for these internal docs links, too?

**Comment by pllim** [comment] 2020-04-06 16:20
I am not familiar with the code here. Where is that code generated?

**Comment by larrybradley** [comment] 2020-04-06 16:29
Those links are dynamically generated by `Sphinx`, specifically the `sphinx.ext.viewcode` extension.  I just noticed that `astropy` turned off showing the source code by setting `plot_html_show_source_link = False` in `docs/conf.py`.

**Comment by pllim** [comment] 2020-04-06 16:32
But where is it generated? Which RST file? 😬

**Comment by larrybradley** [comment] 2020-04-06 16:33
You can pick any of them.  It applies to all `plot::` directives.  @PrasannaJayanthi report specifically refers to https://github.com/astropy/photutils/blob/master/docs/background.rst

**Comment by larrybradley** [comment] 2020-04-06 16:37
It's definitely an upstream issue.  `specutils` has the same issue, e.g. try the "Source code" link above the first plot on this page:  https://specutils.readthedocs.io/en/latest/

**Comment by pllim** [comment] 2020-04-06 16:40
Yeah, definitely, I noticed that in `synphot` as well. 🤔

**Comment by bsipocz** [comment] 2020-04-06 17:03
Yes, it's certainly upstream, but I don't yet see where it's coming from.  Weirdly I don't see it with astroML while messing with the new docs here: https://epyc.astro.washington.edu/~bsipocz/astroml/regression/_build/html/user_guide/regression.html
(while it's annoying there, that I also get the "source code" links for code snippets even though I didn't asked for it.)

**Comment by larrybradley** [comment] 2020-04-06 17:06
Hmm, maybe it's in `sphinx-astropy`?  🤔

**Comment by bsipocz** [comment] 2020-04-06 17:10
Good point, though I don't yet see how, as we don't patch the `plot` directive there.

maybe @astrofrog has insights.

**Comment by pllim** [comment] 2020-04-06 21:24
I don't see how this can add extra slash...

https://github.com/astropy/sphinx-astropy/blob/088f073519a02bd02a9c38dc8b14d81dcc4e69ad/sphinx_astropy/conf/v1.py#L138-L140

**Comment by bsipocz** [comment] 2020-04-07 01:46
oh, that indeed looks like to be it!

Does either of you digging into it, or shall I?

**Comment by pllim** [comment] 2020-04-07 14:52
@bsipocz , I have not gotten to it yet and unlikely this week, so feel free to take it. Thanks! 🙇‍♀

**Comment by bsipocz** [comment] 2020-04-07 15:03
Sounds good,  this will be my rewards project this week then 😅

**Comment by larrybradley** [comment] 2020-04-07 15:15
BTW, on first glance it appeared that was the bug (https://github.com/sphinx-doc/sphinx/blob/f6882d74663438b281a1260684a16e97696ed6d9/sphinx/ext/viewcode.py#L193), but I briefly tried "fixing" it and nothing change.  The bug may be elsewhere.

Also, I noticed that the PNG, PDF, etc. links also have double slashes in the URL (if you look at the HTML source code).  But those links work somehow.

**Comment by pllim** [comment] 2020-04-07 15:20
Still should be avoided regardless. I think it becomes an issue if there is some sort of ambiguity in resolving the server-side contents.

https://stackoverflow.com/questions/20523318/is-a-url-with-in-the-path-section-valid

**Closed** 2024-07-11 20:08 UTC
Labels: bug, docs, upstream fix required
