### ISSUE TITLE
Fitting width of  Moffat2D and Gaussian2D models with PSFPhotometry

### ISSUE THREAD

**Issue by iant321** [astropy/photutils#1670] opened 2023-11-26 20:01 UTC
Hi,

I wrote a code which uses IntegratedGaussianPRF and PSFPhotometry. Works ok, but the fit is not optimal as my measured stellar profiles are non-Gaussian and are more like Moffat. So I tried to implement the Moffat2D model. It works, but it seems that only x, y, and flux (actually amplitude) are fitted and not gamma or alpha. Same with Gaussian2D - x_stddev and y_stddev are not fitted. All these parameters are set to be free in my models. With IntegratedGaussianPRF, if I set

`
psf_model = IntegratedGaussianPRF(flux=1, sigma=fwhm/2.355)
psf_model.sigma.fixed = False
`

sigma of the model is fitted ok. (Yes, I know that this is not good to allow sigma to vary for all sources as the results will be biased for low S/N, what I try to do is to measure sigma for several bright sources and then use this fixed value for the final fit).

My astropy/photutils versions are
astropy 5.3.4
photutils 1.10.0

I was unable to find working examples of how to use Gaussian2D (or Moffat2D) with  PSFPhotometry and would appreciate any help.

For some strange reason a working example which I tried to insert here with "code" formatting was improperly formatted. So I provide a link to the code.  [The code](http://dionis.sai.msu.ru/~igor/test_moffat_gauss.py) can simulate either Moffat or Gaussian stars and then fit them with either Moffat2D or Gaussian2D models. If the initial widths (gamma or x_stddev, y_stddev) for the fit models are wrong, PSFPhotometry does not adjust them. 

I attach a screenshot with the results of the above code. Simulated are Gaussian stars with fwhm=3.0, fitted with initial fwhm=6.0.
![Test_moffat_gauss](https://github.com/astropy/photutils/assets/90242381/315115e0-9ad7-4868-ae77-0766bdc6291e)

**Comment by larrybradley** [comment] 2023-11-27 18:28
I've modified your code to show an example of how to fit a `Moffat2D` PSF model, allowing `gamma` and `alpha` to vary.  Here's an example notebook:

https://gist.github.com/larrybradley/263f2c9c1a47013a38cd71c6690e8105

However, there appears to be bug when the PSF model fit fails (`ValueError: setting an array element with a sequence.`).  Thus, I had to make the initial model parameters closer to the true parameters for the fit to converge.

There are also a few things to note.  When you input an astropy model into `make_psf_model`, the output model is always a `CompoundModel` that "wraps" your input model.  The wrapping maps (or adds) the appropriate x, y, and flux parameters needed for PSF fitting.  So to "unfix" any parameters, you need to use their names in the compound model (e.g., `psf_model.gamma_2.fixed = False`).

Also, "amplitude" is not the same as "flux".  Using it will give the wrong fit "flux" output values unless the input model was already normalized.  Instead of mapping "flux" to "amplitude" just let `make_psf_model` do the normalization and add a scaling parameter that will be the model flux.

Third, one important thing to keep in mind is that when fitting with the models output by `make_psf_model`, the models are evaluated by taking the sample value at pixel centers (this is how astropy modeling works), not integrated over pixel bins.  So a `Gaussian2D` PSF model will give different results than `IntegratedGaussianPRF`, which does integrate over pixel bins.  There is a `PRFAdapter` class that attempts to take an astropy model (e.g., output of `make_psf_model`) and fit with it by integrating over pixel bins.  However, it is *extremely* slow (because of the integrations).  It will be updated in the next release to improve performance by doing approximate integrations.

I'm also planning to add a section in the documentation with these notes and an example.

**Comment by iant321** [comment] 2023-11-27 19:11
Dear Larry,

thanks a lot for your detailed explanations and the code. The solution is very simple, yet it is very hard to find it without having comprehensive knowledge of various photutils components and their interactions.

A few comments:

1. I am aware of the bug as I encountered it myself. Just did not want to mix this into my question. I was going to ask it next. Good to know  that the issue is known and will hopefully be resolved. 

2. Yes, I know about the difference between amplitude and flux. I am just not aware of how to "add scaling parameter" . Again, I postponed this for the future to not complicate things in my original post.

3. I know about the difference between IntegratedGaussianPRF and Gaussian2D but thank you for your explanation. I very much appreciate your good will! Still, with my images I expect to have better results with Moffat. It would be great if integration over pixels would be implemented in the future.

I will now wait for a day for your possible comment on my current post and will close the issue as "solved". Thanks again!

**Comment by larrybradley** [comment] 2023-11-27 22:24
@iant321 I fixed the bug in https://github.com/astropy/photutils/pull/1672.

**Comment by larrybradley** [comment] 2023-11-28 17:50
Many thanks for letting me know!  I'll take a look soon.

**Comment by larrybradley** [comment] 2023-11-29 15:14
@iant321 This appears to be the bug I fixed in #1672.  I cannot reproduce it using the latest dev version (from `main`).  Can you please retry with the latest development version?

`pip install "photutils[all] @ git+https://github.com/astropy/photutils.git"`

**Comment by iant321** [comment] 2023-11-29 21:02
This version of the code works! I have not tested it thoroughly, but running the code on a few 4000x4000 frames worked without any flaws and fitted both gamma and alpha. One strange thing, though. I removed the "flux_name=" mapping from the call to make_psf_model, so PSFPhotometry should compute flux based on the fit values of gamma, alpha, and amplitude. It does, but the value of the flux is ~2 times smaller than the value found with e.g. Gaussian PSF or measured directly within some appropriate aperture (for isolated stars). Yet, the stellar profile is reproduced well. The ratio is approximately the same for various sources so I suspect that the coefficient "2" is lost somewhere when the flux is computed.

Thanks a lot for you work!

**Comment by larrybradley** [comment] 2024-07-11 20:45
@iant321 The issue with the flux values is that the PSF normalization is dependent on the model `alpha` and `gamma` parameters.  The `make_psf_model` output model is normalized *once* using the input `alpha` and `gamma` values, but when you vary them in the fitting, the normalization changes.  Unfortunately, the only way to correct this would be to compute a new normalization scale factor based on the fit `alpha` and `gamma` values for every source individually.  The Moffat profile may have a closed-form formula for its integrated flux based on the model parameters.

**Closed by larrybradley** 2024-07-11 20:45 UTC
Labels: psf

**Comment by larrybradley** [comment] 2024-08-26 23:31
@iant321 I added a `MoffatPSF` class (https://photutils.readthedocs.io/en/latest/api/photutils.psf.MoffatPSF.html) whose normalization is preserved for changes to all parameters. You no longer need to use `make_psf_model`.
