### ISSUE TITLE
travis failing because of matplotlib version

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#270] opened 2015-06-08 14:09 UTC
`travis-ci` is currently failing for the `numpy 1.6` and `1.7` tests because those particular `conda` environments are installing an old version of `matplotlib`, `1.1.1`.  The previous `travis-ci` run for those environments installed `matplotlib 1.3.1`, so it appears something changed with `conda`.  Does anyone know what changed recently (within the past two weeks)?

**Comment by astrofrog** [comment] 2015-06-08 14:26
Will look into it, have been dealing with Travis issues with some other packages.

**Comment by cdeil** [comment] 2015-06-14 18:36
Since today I'm getting this error in Gammapy, this is with matplotlib 1.4.3:
https://travis-ci.org/gammapy/gammapy/jobs/66754236#L1854

It might be completely unrelated to the issue for photutils, but I can't reproduce the Gammapy sphinx build issue locally and photutils seems to be the only other Astropy affiliated package where the travis-ci build is currently broken, so that's how I found this issue:
http://www.astropy.org/astropy-dashboard/status.html

**Comment by bsipocz** [comment] 2015-07-07 11:56
#275 provides a workaround for this.

**Comment by bsipocz** [comment] 2015-08-30 11:32
Closing, as this is fixed now.

**Closed by bsipocz** 2015-08-30 11:32 UTC
Labels: bug, testing
