### ISSUE TITLE
Some tests in photutils/tests/test_aperture_photometry.py fail in linux i386

### ISSUE THREAD

**Issue by sergiopasra** [astropy/photutils#242] opened 2015-01-26 22:38 UTC
Hi, some tests in photutils/tests/test_aperture_photometry.py fail in linux i386, but no in x86_64
More details here:

https://kojipkgs.fedoraproject.org//work/tasks/9826/8719826/build.log

The tests are:
______________ TestElliptical.test_scalar_error_no_effective_gain ______________
____________ TestElliptical.test_scalar_error_scalar_effective_gain ____________
____________ TestElliptical.test_scalar_error_array_effective_gain _____________
______________ TestElliptical.test_array_error_no_effective_gain _______________
_____________ TestElliptical.test_array_error_array_effective_gain _____________
__________ TestEllipticalAnnulus.test_scalar_error_no_effective_gain ___________
________ TestEllipticalAnnulus.test_scalar_error_scalar_effective_gain _________
____ TestEllipticalAnnulus.test_quantity_scalar_error_scalar_effective_gain ____
_________ TestEllipticalAnnulus.test_scalar_error_array_effective_gain _________
___________ TestEllipticalAnnulus.test_array_error_no_effective_gain __________
_________ TestEllipticalAnnulus.test_array_error_array_effective_gain __________

**Comment by bsipocz** [comment] 2015-01-26 23:39
I'll check tomorrow whether I can find a running i386 Python somewhere, and
will fix these.

**Comment by cdeil** [comment] 2015-01-27 05:10
@sergiopasra Thanks for testing!

@astrofrog @larrybradley @bsipocz Do you think we should support 32-bit machines for photutils?

I'm -1 because it's extremely rare these days and we don't have developers / continuous integration using 32-bit, so it's annoying to support.

I've been bitten many times where I accidentally used 32-bit images and got (sometimes completely, sometimes slightly) incorrect results when summing over many pixels, so for Gammapy I've adopted a ["do computations with `float64`" policy](https://gammapy.readthedocs.org/en/latest/development/index.html#float-data-type-32-bit-or-64-bit)

**Comment by bsipocz** [comment] 2015-01-27 10:55
It would nice to support 32bit IF we could get a testing system up and
running. Testing and developing on an archaic a gateway server or on the
grandparents desktop (these are the only ones I've found), is definitely
not a good solution.
To be honest I'm not surprised that those test fail...

**Comment by astrofrog** [comment] 2015-01-27 11:02
Just to make sure I understand, are 32-bit systems incapable of using ``np.float64`` or is it just that the default is ``np.float32``? If the latter then we can still support those systems by casting any input to ``np.float64``, right?

**Comment by cdeil** [comment] 2015-01-27 11:07
@sergiopasra Please correct me if I'm wrong, but I think 32-bit systems do now support 64-bit floats like `np.float64`. I'm not sure what happens ... but `np.float128` definitely doesn't give me 128 bit float precision on my 64-bit machine (that would be nice).

@bsipocz It wouldn't be super-hard to create a VM or Docker container with a Linux 32-bit OS (see e.g. instructions [here](https://github.com/gammapy/gammapy/blob/master/dev/docker/commands.sh)), but I don't think it's useful to support.

**Comment by astrofrog** [comment] 2015-01-27 11:08
I think what we do need to make sure of is that photutils works with 32-bit images and arrays (even if it converts to 64-bit internally). Some FITS files return 32-bit. So if we make sure it can work regardless of the input, I think we may implicitly manage to support 32-bit systems.

**Comment by cdeil** [comment] 2015-01-27 12:09
@astrofrog - I only briefly looked at the test failures, but I think the issue is not that photutils doesn't work with 32-bit inputs, it's that accumulating results in 32-bit gives inaccurate results if you sum e.g. for lots of pixels. We could (and maybe should) change to use 64-bit accumulators in all `np.sum` etc. calls, so that users on 64-bit machines get good results even if they pass 32-bit data in.
But the tests would still fail on 32-bit systems, I think, because it just doesn't support 64-bit float arithmetic.

**Comment by bsipocz** [comment] 2015-01-27 12:18
I'm afraid this uncovered a real a bug somewhere deeper. The result of the following summing of np.ones depends on whether it was run on a 64 or 32bit system (90 or 92 respectively). Insensitive to the dtype of ``data``, but sensitive to the position.

```
import astropy.units as u
from photutils import *
data = np.ones((40, 40), dtype=np.float)
position = (20., 20.)
a_in = 5.
a_out = 8.
b_out = 6.
theta = -np.pi / 4.
aperture = EllipticalAnnulus(position, a_in, a_out, b_out, theta)
table1 = aperture_photometry(data, aperture, method='center', mask=mask, error=error)
table1['aperture_sum']
```

**Comment by sergiopasra** [comment] 2015-01-27 13:02
@cdeil Numpy in i386 supports np.float64. I get the following in a Fedora 20 i386 virtual machine, numpy is 1.8.2

```python
>>> import numpy as np
>>> print np.zeros((10, 10)).dtype
dtype('float64')
```

There is a very long thread about numeric precision of ``np.mean`` in the numpy list. 
http://mail.scipy.org/pipermail/numpy-discussion/2014-July/070740.html
I think it can be relevant

**Comment by astrofrog** [comment] 2015-01-27 13:07
@bsipocz - can you rerun your example but with ``np.float64`` instead of ``np.float``? (not sure if the two are equivalent on 32-bit systems?)

**Comment by bsipocz** [comment] 2015-01-27 14:03
Yes, no difference. The bug is in ``EllipticalAperture``, in case when
``a==b`` is should return the same as ``CircularAperture``. Maybe this is
related to #198.

```
from photutils import *
data = np.ones((40, 40), dtype=np.float64)
data1 = np.ones((40, 40), dtype=np.float32)
position = (20., 20.)
a = 6.
b = 6.
theta = 0
aperture = EllipticalAperture(position, a, b, theta)
aperture1 = CircularAperture(position, a)
aperture_photometry(data, aperture, method='center')
aperture_photometry(data, aperture1, method='center')
aperture_photometry(data1, aperture, method='center')
aperture_photometry(data1, aperture1, method='center')

Out[24]:
<Table masked=False length=1>
aperture_sum xcenter [1] ycenter [1]

  float64      float64     float64
------------ ----------- -----------
       113.0        20.0        20.0

In [25]: aperture_photometry(data, aperture1, method='center')
Out[25]:
<Table masked=False length=1>
aperture_sum xcenter [1] ycenter [1]

  float64      float64     float64
------------ ----------- -----------
       109.0        20.0        20.0

In [26]: aperture_photometry(data1, aperture, method='center')
Out[26]:
<Table masked=False length=1>
aperture_sum xcenter [1] ycenter [1]

  float64      float64     float64
------------ ----------- -----------
       113.0        20.0        20.0

In [27]: aperture_photometry(data1, aperture1, method='center')
Out[27]:
<Table masked=False length=1>
aperture_sum xcenter [1] ycenter [1]

  float64      float64     float64
------------ ----------- -----------
       109.0        20.0        20.0
```

**Comment by bsipocz** [comment] 2015-01-27 18:13
The difference is due to the different functions used in the cython code to
figure out the overlap, whether a centre of a pixel is within the aperture.
I think this can be traced back to the float precision in the corresponding
c code, and not sure it's worth tempering with. It's happening in only a
small fraction of the corner cases when the aperture goes through the
centre. The maximum difference I could make was 4 pixels, (which seem to be
significant for small apertures, but bigger differences can be made just by
positioning the aperture at a slightly different centre coordinate). Using
the method ``center`` is an approximation to begin with, and needless to
say the result won't change with the dtype of the data, etc.

I suggest that we regard this as an artefact of the float comparison, and
I'll fix the tests to use a different radius that works.

**Comment by bsipocz** [comment] 2015-01-28 15:37
@cdeil, @astrofrog, @larrybradley - 
#245 adjust the tests to pass on 32bit, but it doesn't change the cython code.

**Comment by cdeil** [comment] 2015-01-28 15:53
So the problem with results changing for 32-bit or 64-bit occurs when pixel centers are located on aperture edges?
Hmmm ... I guess this is hard to avoid when adding / changing tests in the future ... is it possible to find a solution to prevent this issue coming up again in the future?

The only idea I have is a `CHECK_STABLE=True/False` option at the top that changes the aperture extensions by +- 1% would help? Developers set it to true and then it runs the tests 3 times with 0.99, 1.00 and 1.01 times ... this will only work if there are no pixel centers at the aperture edges.
And then on user / Debian testing machines there's `CHECK_STABLE = False` and the test only runs for the nominal extensions we have now (factor 1.00), but we are sure that the tests will not be susceptible to this issue any more.

**Comment by bsipocz** [comment] 2015-01-28 16:31
Yes, I guess that's the source of the problem. 
However this the discrepancy is only present in about half the cases. (e.g. radius 4, 5, 8, 11 work (with the centre position on a grid point), however 3, 6, 7, 12 don't).

#245 uses this 'feature', and thus the tests pass, so I think in that case your suggestion of ``CHECK_STABLE`` is unnecessary. Ever more straightforward would be to use none a fractional radius size, those weren't problematic.

**Comment by cdeil** [comment] 2015-01-28 16:57
Even with a fractional pixel size as aperture radius you can come arbitrary close to pixel centers ... I don't have a good suggestion for how to handle this testing issue better, so +1 to committing your fix now (maybe adding a comment explaining the issue with one sentence and linking to this issue) and see if someone else gets such errors in the future.

**Comment by bsipocz** [comment] 2015-01-28 20:54
@sergiopasra - Could you please check whether the tests pass now that #245 is merged?

**Comment by sergiopasra** [comment] 2015-01-29 10:21
@bsipocz No, I still get  errors. I have tested in  a i386 VM with numpy 1.8.2 and scipy 0.12.1

Full output of pytest
http://guaix.fis.ucm.es/~spr/github/photutils-242-pytest1.text

**Comment by bsipocz** [comment] 2015-01-30 17:44
@sergiopasra - sadly I cannot reproduce the error, even with the same numpy and scipy. And these ones are most probably not related to the  float precision, as the actual value for ``'aperture_sum'`` seems to be a factor of 3 larger than expected.

```
Platform: Linux-3.2.0-4-686-pae-i686-with-debian-7.8

Executable: /usr/bin/python

Full Python Version: 
2.7.3 (default, Mar 14 2014, 11:57:14) 
[GCC 4.7.2]

encodings: sys: ascii, locale: ISO-8859-1, filesystem: ISO-8859-1, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15

Numpy: 1.8.2
Scipy: 0.12.1
Matplotlib: 1.4.2
scikit-image: 0.10.1
astropy: 1.1.dev11780
```

**Comment by sergiopasra** [comment] 2015-02-02 09:41
@bsipocz Let me try with a different VM

**Comment by sergiopasra** [comment] 2015-02-05 10:56
@bsipocz I still get the errors. I have installed a debian 8 VM and the errors apper in the same places. I have used astropy and photutils from master.

```
============================= test session starts ==============================
platform linux2 -- Python 2.7.8 -- py-1.4.25 -- pytest-2.6.3
 
Running tests with Astropy version 1.1.dev1298.
Running tests in photutils/.
 
Platform: Linux-3.16.0-4-686-pae-i686-with-debian-8.0
 
Executable: /usr/bin/python
 
Full Python Version:
2.7.8 (default, Oct 18 2014, 16:20:11)
[GCC 4.9.1]
 
encodings: sys: ascii, locale: UTF-8, filesystem: UTF-8, unicode bits: 20
byteorder: little
float info: dig: 15, mant_dig: 15
 
Numpy: 1.8.2
Scipy: 0.14.0
Matplotlib: not available
scikit-image: not available
astropy: 1.1.dev1298 
```
https://gist.github.com/sergiopasra/23975871668fe83b93d4

**Comment by bsipocz** [comment] 2015-02-05 18:39
@cdeil, @astrofrog, @larrybradley - I'm at my wit's end with this.  I tried to reproduce it on two different setups with no success. However it is quite suspicious to be a bug as there is a factor of 3 difference between the expected and actual values.

**Comment by cdeil** [comment] 2015-02-05 22:29
It's suspicious that the sum in the elliptical aperture is exactly a factor 3 higher after calling `aperture_photometry` 3 times (but only for the elliptical aperture) ... I was looking through the code a bit for possible modification of the input `data` but don't see anything that would lead to it changing.

@sergiopasra Do numpy and Astropy unit tests pass on that machine? Is there a simple way to duplicate the VM where you see the issue, e.g. with Vagrant? If a `photutils` dev could reproduce the issue it would probably not be hard to track down e.g. by adding print statements in a few places.

**Comment by sergiopasra** [comment] 2015-02-06 13:27
@cdeil I'm just testing in Fedora 20, Fedora 21 and Debian 8 VM under QEMU/KVM Fedora 21, I installed them with a Live CD, nothing esoteric

I have debugged this a little bit. The problem seems to be this test

```python
class TestElliptical(BaseTestAperturePhotometry):

    def setup_class(self):
        self.data = np.ones((40, 40), dtype=np.float)
        position = (20., 20.)
        a = 10.
        b = 5.
        theta = -np.pi / 4.
        self.aperture = EllipticalAperture(position, a, b, theta)
        self.area = np.pi * a * b
        self.true_flux = self.area
```
But only when `theta` is `+-np.pi / 4` and method is `exact`. If I change the angle to, say, 0.1, then the test passes.

The number of calls to `aperture_photometry` doesn't affect the outcome.

I have traced the problem upto a call to `elliptical_overlap_grid` inside `do_elliptical_photometry`
As far as I can see, the inputs of this function are identical in the test cases (except `use_exact` and `subpixel`) but the output of `exact`is quite different.

A call to `elliptical_overlap_grid(-10.5, 10.5, -10.5, 10.5, 21, 21, 10.0, 5.0, -0.785398163397, 0, 12)` returns an array `fraction`, with min of 0, max of 1, and a sum of 157.

![figure_1](https://cloud.githubusercontent.com/assets/890104/6079658/7b4f17e0-ae08-11e4-86dd-515a4aa4ac67.png)

But a call to `elliptical_overlap_grid(-10.5, 10.5, -10.5, 10.5, 21, 21, 10.0, 5.0, -0.785398163397, 1, 1)` returns an array `fraction`, with min of 0, and two points with value ~157 each (the red points), the rest are between 0 and 1

![figure_w](https://cloud.githubusercontent.com/assets/890104/6079910/b9fa3b7a-ae0b-11e4-82ee-eabfe95efccd.png)

Whatever happens is inside `elliptical_overlap_grid`

**Comment by bsipocz** [comment] 2015-02-06 13:34
@sergiopasra what is the version combination for the libc/gcc in these setups?

**Comment by sergiopasra** [comment] 2015-02-06 15:40
@bsipocz In debian 8 gcc 4.9.1, fedora 21 has gcc 4.9.2 and Fedora 20 gcc 4.8.3

**Comment by sergiopasra** [comment] 2015-02-06 15:55
@cdeil I'm now looking inside `overlap_area_triangle_unit_circle`
In the wrong pixels, one of the two triangles has its vertex `x1`, `y1` **on** the circle (`d1` = 1)

The routine determines which vertices are inside and which are on the circle. 

``` cython
   # Determine number of vertices inside circle
    in1 = d1 < 1
    in2 = d2 < 1
    in3 = d3 < 1

    # Determine which vertices are on the circle
    on1 = fabs(d1 - 1) < 1.e-10
    on2 = fabs(d2 - 1) < 1.e-10
    on3 = fabs(d3 - 1) < 1.e-10
```
For `x1, y1` both are true. Later there are several choices

``` cython
if on3 or in3:  # triangle is completely in circle
   ...
elif in2 or on2:
  ...
elif in1:
  ...
else:
  ...
```
Notice that there isn't a check for `on1`. But if `on1` is true, the triangle is completely outside the circle and the are should be 0.0. is that correct?

**Comment by cdeil** [comment] 2015-02-06 19:15
@sergiopasra Thanks for taking the time to debug and fix this issue!

**Closed** 2015-07-13 15:09 UTC
Labels: aperture, bug
