### ISSUE TITLE
About PSF model

### ISSUE THREAD

**Issue by sailoryf** [astropy/photutils#728] opened 2018-09-27 04:48 UTC
Hi,
When I got the PSF model from EPSFBuilder. Could the model be used as the parameter in IterativelySubtractedPSFPhotometry: psf_model? It raise the error lile:
File "/home/yf/.conda/envs/python3/lib/python3.6/site-packages/photutils/aperture/circle.py", line 124, in __init__
    if r < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
Is that mean the EPSFBuilder does not return a proper 2D PSF model, or I made mistakes somewhere.

**Comment by mjrfringes** [comment] 2018-10-03 18:13
I have the same issue. I am trying to get the PSF model from EPSBuilder, and feed that as a psf model to IterativelySubtractedPSFPhotometry, and it gives me the following error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-49-71ea0706c6a7> in <module>()
     24                                                 fitter=LevMarLSQFitter(),
     25                                                 fitshape=(9,9))
---> 26 result_tab = photometry(data)
     27 residual_image = photometry.get_residual_image()

~/anaconda2/envs/py36/lib/python3.6/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    486                         # one with the name of the new argument to the function
    487                         kwargs[new_name[i]] = value
--> 488             return function(*args, **kwargs)
    489 
    490         return wrapper

~/anaconda2/envs/py36/lib/python3.6/site-packages/photutils/psf/photometry.py in __call__(self, image, init_guesses)
    187         """
    188 
--> 189         return self.do_photometry(image, init_guesses)
    190 
    191     @deprecated_renamed_argument('positions', 'init_guesses', '0.4')

~/anaconda2/envs/py36/lib/python3.6/site-packages/astropy/utils/decorators.py in wrapper(*args, **kwargs)
    486                         # one with the name of the new argument to the function
    487                         kwargs[new_name[i]] = value
--> 488             return function(*args, **kwargs)
    489 
    490         return wrapper

~/anaconda2/envs/py36/lib/python3.6/site-packages/photutils/psf/photometry.py in do_photometry(self, image, init_guesses)
    664                                             gaussian_sigma_to_fwhm)
    665 
--> 666             output_table = self._do_photometry(['x_0', 'y_0', 'flux_0'])
    667         return output_table
    668 

~/anaconda2/envs/py36/lib/python3.6/site-packages/photutils/psf/photometry.py in _do_photometry(self, param_tab, n_start)
    705             apertures = CircularAperture((sources['xcentroid'],
    706                                           sources['ycentroid']),
--> 707                                          r=self.aperture_radius)
    708             sources['aperture_flux'] = aperture_photometry(
    709                 self._residual_image, apertures)['aperture_sum']

~/anaconda2/envs/py36/lib/python3.6/site-packages/photutils/aperture/circle.py in __init__(self, positions, r)
    122 
    123     def __init__(self, positions, r):
--> 124         if r < 0:
    125             raise ValueError('r must be non-negative')
    126 

TypeError: '<' not supported between instances of 'NoneType' and 'int'

**Comment by Onoddil** [comment] 2018-10-09 02:03
This issue is caused by the calling of ``IterativelySubtractedPSFPhotometry`` with ``aperture_radius`` at its default value ``None``. Thus ``r`` is `NoneType` when the radius is passed into circle.py. The current implementation will only attempt to derive a radius if the PSF model passed has either a FWHM or sigma attribute (typically because the PSF is a Gaussian), but the ePSF is an empirical 2D model and thus has no such attribute. 

I have submitted a fix for this, and temporarily suggest a similar workaround for the time being: pass a value for ``aperture_radius`` when doing PSF photometry with an effective PSF model -- the default fallback radius I suggested is the smaller of the two pixel lengths (i.e., a radius of ``(x - 1)/2`` where ``x`` is the width of the fitting box), but any acceptable radius should hopefully solve the issue.

**Closed** 2019-07-29 19:05 UTC
Labels: bug, psf

**Comment by astrobatty** [comment] 2021-01-22 20:24
Hi,
this issue is still in the code as the PR added a bugfix to the `BasicPSFPhotometry` class and not to `IterativelySubtractedPSFPhotometry`. If I run `IterativelySubtractedPSFPhotometry` with a PSF from `EPSFBuilder` I get this message:

```
ValueError                                Traceback (most recent call last)
<ipython-input-96-4bc4310cb621> in <module>
     34                                                 niters=1, fitshape=(13,13))
     35 
---> 36 result_tab = photometry(image=image)
     37 residual_image = photometry.get_residual_image()

~/opt/miniconda3/lib/python3.7/site-packages/photutils/psf/photometry.py in __call__(self, image, init_guesses)
    199         """
    200 
--> 201         return self.do_photometry(image, init_guesses)
    202 
    203     def do_photometry(self, image, init_guesses=None):

~/opt/miniconda3/lib/python3.7/site-packages/photutils/psf/photometry.py in do_photometry(self, image, init_guesses)
    733                                             gaussian_sigma_to_fwhm)
    734 
--> 735             output_table = self._do_photometry()
    736         return output_table
    737 

~/opt/miniconda3/lib/python3.7/site-packages/photutils/psf/photometry.py in _do_photometry(self, n_start)
    771                                       sources['ycentroid']))
    772             apertures = CircularAperture(positions,
--> 773                                          r=self.aperture_radius)
    774             sources['aperture_flux'] = aperture_photometry(
    775                 self._residual_image, apertures)['aperture_sum']

~/opt/miniconda3/lib/python3.7/site-packages/photutils/aperture/circle.py in __init__(self, positions, r)
    147     def __init__(self, positions, r):
    148         self.positions = positions
--> 149         self.r = r
    150 
    151     @property

~/opt/miniconda3/lib/python3.7/site-packages/photutils/aperture/attributes.py in __set__(self, instance, value)
     27 
     28     def __set__(self, instance, value):
---> 29         self._validate(value)
     30         if not isinstance(value, (u.Quantity, SkyCoord)):
     31             value = float(value)

~/opt/miniconda3/lib/python3.7/site-packages/photutils/aperture/attributes.py in _validate(self, value)
    116     def _validate(self, value):
    117         if not np.isscalar(value) or value <= 0:
--> 118             raise ValueError('{} must be a positive scalar'.format(self.name))
    119 
    120 

ValueError: r must be a positive scalar
```

Therefore, I had to dig into the code and search through the issues to find an already known and "fixed" bug. So, the same solution should be added to`IterativelySubtractedPSFPhotometry`, somewhere [here](https://github.com/astropy/photutils/blob/60ba393ec35f83b4b25fbb0578cd9cca9300a36f/photutils/psf/photometry.py#L713).

**Comment by TSA26** [comment] 2021-03-11 07:40
This issue is still not solved
