### ISSUE TITLE
Cannot `import photutils` in a Google Colab notebook

### ISSUE THREAD

**Issue by barentsen** [astropy/photutils#964] opened 2019-10-09 19:46 UTC
It does not appear to be possible to import `photutils` on the Google Colab platform!

I tried the following:
1. Browse to https://colab.research.google.com and click "New Python 3 Notebook"
2. Runtime > Reset all runtimes  (just in case)
3. Execute `!pip install photutils` (this works fine)
4. Execute `import photutils`

Step 4 yields the following exception:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-e3d8b5fe96af> in <module>()
----> 1 import photutils

5 frames
/usr/local/lib/python3.6/dist-packages/astropy/utils/decorators.py in decorator(function)
    443                                 'signature. If it was meant to be part of '
    444                                 '"**kwargs" then set "arg_in_kwargs" to "True"'
--> 445                                 '.'.format(new_name[i]))
    446 
    447         @functools.wraps(function)

TypeError: "None" was not specified in the function signature. If it was meant to be part of "**kwargs" then set "arg_in_kwargs" to "True".
```

Screenshot:
![Screenshot from 2019-10-09 12-40-41](https://user-images.githubusercontent.com/817669/66514804-be479d80-ea92-11e9-8050-3d84dff70d12.png)

**Comment by bsipocz** [comment] 2019-10-09 19:48
what is your astropy version?

**Comment by barentsen** [comment] 2019-10-09 19:55
Google Colab runtimes appear to have Astropy 3.0.5 installed by default.

I confirm that running `!pip install astropy==3.2` fixes the issue and enables photutils to be imported, screenshot:
![Screenshot from 2019-10-09 12-54-13](https://user-images.githubusercontent.com/817669/66515391-ea175300-ea93-11e9-956f-aec88008f256.png)

I would have expected astropy to be updated automatically upon the initial `!pip install photutils`? Is my expectation incorrect?

**Comment by bsipocz** [comment] 2019-10-09 19:58
that must be some mess in colab, photutils 0.7.1 has a clearly stated requirement of astropy >=3.2 in it's setup file.

**Comment by bsipocz** [comment] 2019-10-09 19:59
(maybe their pip is too old? I'm just guessing around)

**Comment by barentsen** [comment] 2019-10-09 20:05
I think there is a legitimate packaging bug on the photutils side.  When I run `pip install photutils` in linux I see the message:
```
Requirement already satisfied: astropy>=2.0
```

Indeed, downloading the wheel directly from pypi, I find:
```
$ wget https://files.pythonhosted.org/packages/28/cd/cb82fe35dc9f333bf54259fe5013690f4ef01aef4dfe677a2d26c37f0698/photutils-0.7.1-cp37-cp37m-manylinux1_x86_64.whl
$ unzip photutils-0.7.1-cp37-cp37m-manylinux1_x86_64.whl
$ cat photutils-0.7.1.dist-info/METADATA | grep "astropy "
Requires-Dist: astropy (>=2.0)
```

It looks like the `install_requires` information in `setup.cfg` may not be passed on somewhere in the chain?

**Comment by bsipocz** [comment] 2019-10-09 20:07
Ohh, you're right. It's 3.2 on the dev branch, rather than on the bugfix branch. We need to get this sorted then.
(I think the solution is that 2.0.x branch is OK, but then it has to be newer, probably on 3.1.x? will investigate)

**Comment by larrybradley** [comment] 2019-10-09 20:08
`photutils 0.7.1` (*just* released) should require `astropy >= 2.0`.  That is also what is in `setup.cfg`.  @bsipocz Where did you see that `photutils 0.7.1` requires `astropy >= 3.2`?

**Comment by larrybradley** [comment] 2019-10-09 20:14
It also fails with `photutils 0.7` on Google Coab.

@barentsen Did any version of photutils work there with `astropy 3.0.5`?

**Comment by bsipocz** [comment] 2019-10-09 20:18
My suspicion is that `astropy.utils` has changed since 3.0.5, and 2.0.x got the backports but not 3.0.x. Can investigate in the weekend (or maybe this evening).

**Comment by barentsen** [comment] 2019-10-09 20:33
@larrybradley The latest version that seems to works on Google Colab is 0.4.0.

**Comment by larrybradley** [comment] 2019-10-09 20:51
@bsipocz That makes sense.  Thanks!

**Comment by larrybradley** [comment] 2019-10-09 20:52
The good news is this doesn't appear to be an issue because something was wrong with the 0.7.1 release.

**Comment by larrybradley** [comment] 2019-10-09 20:56
side note:  How do we get Google Coab to install `astropy 3.2.x` as the default?

**Comment by bsipocz** [comment] 2019-10-09 21:15
yes, it's interesting. They should either stick with 2.0.x or go to actual latest, 3.2.x

**Comment by bsipocz** [comment] 2019-10-09 21:47
OK. So the issue is that `photutils` uses the remove argument feature of the `deprecated_renamed_argument` decorator, that has been added in https://github.com/astropy/astropy/pull/8324, and made available in 2.0.12 and in 3.1.2, so we should really have a requirement of astropy as:

`astropy>=2.0.12,!=3.0.*, !=3.1,!=3.1.1`

**Comment by larrybradley** [comment] 2019-10-09 21:56
Thanks for tracking this down.  That's my fault for not checking when `deprecated_renamed_argument` was first available in `astropy`.  The photutils CI tests were probably testing against only astropy `2.0.x`and `>= 3.1.2` when I used it in photutils.

@barentsen Many thanks for reporting this!

**Comment by bsipocz** [comment] 2019-10-09 22:00
This was a very rare case for adding a feature in mid release cycle (I really needed it downstream, and didn't think about it hard that it will be picked up by others, too).

But I agree, that we better have a more complete test matrix, e.g. sticking to the first edition of a bugfix branch? e.g. test with astropy 2.0, 3.0, 3.1, 3.2 and dev rather than letting it pick up the latest of each?

cc @astrofrog @eteq

**Comment by bsipocz** [comment] 2019-10-09 22:00
I'm also adding this issue of testing to the coordination meeting's agenda, worth going through the options.

**Comment by larrybradley** [comment] 2019-10-09 23:45
#965 should have closed this, but somehow didn't.

**Closed by larrybradley** 2019-10-09 23:45 UTC
Labels: bug, installation, releases
