### ISSUE TITLE
Improve performance of ellipse fitting where possible

### ISSUE THREAD

**Issue by larrybradley** [astropy/photutils#802] opened 2019-02-28 17:38 UTC
Creating this issue as a reminder.  CC @moustakas

**Comment by moustakas** [comment] 2019-03-21 20:35
Thanks, @larrybradley.  I've done some very basic profiling of the code using `cProfile` and `snakeviz` (see below), but I'm hoping you will have more insight.  One of the biggest bottlenecks appears to be the `geometry.to_polar` method, which is called by `integrate.integrator`, as well as `sample._get_gradient`.  I'll try to dig some more but I'm hopeful this is enough to get things started.

<img width="913" alt="Screen Shot 2019-03-21 at 4 33 05 PM" src="https://user-images.githubusercontent.com/1431820/54783230-346bdc00-4bf7-11e9-9165-8b07c4f881cb.png">

To reproduce my results, grab and unzip [this image](https://github.com/astropy/photutils/files/2993787/image.fits.zip), put the code snippet pasted below into a script (I called it `profile-ellipsefit.py`) and then do

```bash
pip install snakeviz
python -m cProfile -o profile-ellipsefit.prof profile-ellipsefit.py
snakeviz profile-ellipsefit.prof
```

```python
#!/usr/bin/env python

import fitsio
import numpy.ma as ma
from photutils.isophote import EllipseGeometry, Ellipse

img = fitsio.read('image.fits')
img = ma.masked_array(img, img==0)

g = EllipseGeometry(x0=266, y0=266, eps=0.240, sma=110, pa=1.0558)
ell = Ellipse(img, geometry=g)
iso = ell.fit_image(3, integrmode='median', sclip=3, nclip=2, linear=False, step=0.1)
```

**Comment by moustakas** [comment] 2019-03-21 20:52
Digging a bit more, it looks like the `to_polar` method is being called many times *for the same input pixels*.  If the transformed coordinates can be pre-computed and cached that should yield significant compute savings.

**Comment by moustakas** [comment] 2019-04-09 15:24
@larrybradley @ibusko 

I wonder if you've been able to take a look at this issue and whether you think there are any low-hanging speed-ups to the `fit_image` method?

**Comment by ibusko** [comment] 2019-04-09 15:34
@moustakas you're right that there are bottlenecks in the code. Ages ago I had done a similar cProfile-snakeviz analysis like yours, and came to the conclusion that to significantly speed-up the code we would have to resort to C. I don't recall having python-level bottlenecks as the redundant calls to to_polar(), but I may have just not noticed that. I will take a look as soon as possible into that. 

Thanks for the detailed analysis!

**Comment by ibusko** [comment] 2019-04-11 19:09
I can reproduce @moustakas' profiling results, including a surprising very large fraction of the time being taken by the one method, `to_polar`. I don't really recall that being the case when I did run these profiling tests a long ago.

I can also measure a significant degradation in computation speed from the original inception's version of the code. In tutorial `isophote_example4.ipynb` in `photutils-datasets`, I recorded at that time that the entire script would take about 40 min. to complete on a Mac Pro 3.7 GHz Xeon E5. Now, on a similar machine, it tool about 3.5 hours. 

I wonder if both findings have anything to do with the vectorization of the scalar computation in `to_polar`.

As for caching the results of `to_polar`, it might be feasible to do, but I will try first to roll back the code to the non-vectorized version and see if that improves or degrades the performance further.

**Comment by larrybradley** [comment] 2019-04-11 19:25
@ibusko  Hopefully I didn't make things slower by vectorizing `to_polar`!  My apologies if that's the case.  I recall things being faster after removing some `for` loops in favor of vectorization.

**Comment by ibusko** [comment] 2019-04-11 21:18
@larrybradley OK, no worries. I will run some experiments and see how we can improve that.

**Comment by bsipocz** [comment] 2019-04-11 21:21
I wonder whether there are enough resources to resurrect https://github.com/astropy/photutils-benchmarks and add more benchmarks?

**Comment by moustakas** [comment] 2019-04-11 22:39
Great to see so much activity on this thread!

Another suggestion for some of the under-the-hood geometric calculations is to use [https://numba.pydata.org](numba) (in lieu of refactoring to C-code), which could be brought in as an *optional* dependence.

But I agree that we should first track down why the code slowed down by a factor of 5 after it was ostensibly vectorized.

**Comment by ibusko** [comment] 2019-04-12 15:22
I run tests with the non-vectorized version of `to_polar`. The bottleneck uncovered by cProfile in `to_polar` went from 40 s to 4.6 s tottime as reported by snakeviz. The overall test was increased in speed by a factor ~5. No specific, easy-to-pin-down bottlenecks remain; the CPU consumption is spread more or less evenly inside the integrator classes, with most of the time spent inside `numpy/ma` in `core.py`.

The version I have in place in my dev area uses a poor-man's hybrid version of `to_polar`, which includes both versions of code, vectorized and non-vectorized, selected by a conditional on the input data type. This is because there are parts of the code that call `to_polar` with an actual nXn numpy array, instead of a scalar. For these array parts, the vectorized code is still needed. I will figure out a way of doing this in a more elegant way.

**Comment by ibusko** [comment] 2019-04-18 16:43
Did some more profiling with @moustakas' test example. We knew already that the use of masked arrays slows down the computations quite a bit. I removed the masked array from the test, running fit_image on the raw image. 

In this case, the to_polar calls become a no-issue, with most of the CPU burden now placed in the integrator classes. Replacing the median integrator with the bi-linear one didn't make much of a difference in relative load terms. Overall, the fit speeds up (as we know already), but the main load is still located in the integrator code.

I'm filing a PR with this modified code (vectorized AND scalar versions of to_polar), keeping in mind that there is more room for improvement still.

**Comment by moustakas** [comment] 2019-04-19 03:11
Thanks, @ibusko, I'm looking forward to your PR, which I'd be happy to test independently.  And if you have any recommendations for dealing with masked pixels while not compromising performance (presumably not using `numpy.ma` arrays), I'd be grateful.

**Comment by ibusko** [comment] 2019-04-19 18:06
Closing after sucessfull resolution.

**Closed** 2019-04-19 20:04 UTC
Labels: isophote, performance
