### ISSUE TITLE
Odd error message

### ISSUE THREAD

**Issue by russel** [astropy/photutils#431] opened 2016-09-24 16:48 UTC
Using photutils (0.2.2) with Python 3 (3.5.2) and PIL (1.1.7 via packaging, actually pillow 3.3.1) on Debian Sid, the code:
```python
from PIL import Image
from photutils import background, detect_threshold, detect_sources

data = Image.open('AHZ2001c0z.jpg')
bkg = background.Background(data, (50, 50), filter_shape=(3, 3), method='median')
```
(strip down from the person's real code) results in the error:
```
Traceback (most recent call last):
  File "bug_report.py", line 5, in <module>
    bkg = background.Background(data, (50, 50), filter_shape=(3, 3), method='median')
  File "/usr/lib/python3/dist-packages/photutils/background.py", line 134, in __init__
    self.box_shape = (min(box_shape[0], data.shape[0]),
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 627, in __getattr__
    raise AttributeError(name)
AttributeError: shape
```
This error message is weird: there is no indication what is to be done in the user code to avoid this problem. Unless I am missing something.

**Comment by larrybradley** [comment] 2016-09-26 21:06
@russel  Thanks for your report.  The issue is that `Image.open()` returns a `PIL` object instead of an `numpy.ndarray` and the `PIL` object doesn't have a `shape` attribute.

We usually perform the conversion to an `ndarray` internally, but unfortunately `Background` is missing that feature (it expects `data` to be an ndarray).  It will be fixed in the next release to allow an "array-like" input, but in the meantime you should be able to convert it yourself by adding a line `data = np.asarray(data)`, e.g.:

```
from PIL import Image
from photutils import background, detect_threshold, detect_sources

data = Image.open('AHZ2001c0z.jpg')
data = np.asarray(data)
bkg = background.Background(data, (50, 50), filter_shape=(3, 3), method='median')
```

**Comment by russel** [comment] 2016-09-27 12:37
@larrybradley Thanks for letting me know.  I tried the code above with the addition of import of NumPy:
```
from PIL import Image
from photutils import background, detect_threshold, detect_sources

import numpy

data = Image.open('AHZ2001c0z.jpg')
data = numpy.asarray(data)
bkg = background.Background(data, (50, 50), filter_shape=(3, 3), method='median')
```
But this leads to:
```
Traceback (most recent call last):
  File "bug_report_431_solution.py", line 8, in <module>
    bkg = background.Background(data, (50, 50), filter_shape=(3, 3), method='median')
  File "/usr/lib/python3/dist-packages/photutils/background.py", line 150, in __init__
    data_ma = self._pad_data(data, mask)
  File "/usr/lib/python3/dist-packages/photutils/background.py", line 172, in _pad_data
    constant_values=[np.nan])
  File "/home/users/russel/.local/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1318, in pad
    pad_width = _validate_lengths(narray, pad_width)
  File "/home/users/russel/.local/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1103, in _validate_lengths
    normshp = _normalize_shape(narray, number_elements)
  File "/home/users/russel/.local/lib/python3.5/site-packages/numpy/lib/arraypad.py", line 1058, in _normalize_shape
    raise ValueError(fmt % (shape,))
ValueError: Unable to create correctly shaped tuple from ((0, 26), (0, 26))
```

**Comment by larrybradley** [comment] 2016-09-27 16:48
Ah, one other thing you need to do is "flatten" your image to a 2D ndarray.  PIL will load your JPG image as a 3D N x M x 3 image (for RGB; NxMx4 for RGBA), i.e. one 2D image each in R, G, and B.  `Background` requires a 2D image, but you can convert your RGB image to a 2D grayscale `numpy.ndarray` like this:

```
data = Image.open('AHZ2001c0z.jpg').convert('L')
data = numpy.asarray(data)
```

**Comment by larrybradley** [comment] 2016-10-24 17:56
@russel Hopefully this solved your problem, but please re-open this issue if you are still having trouble.

**Closed by larrybradley** 2016-10-24 17:56 UTC
Labels: background
